[workspace]
resolver = "3"
members = [
  "init",
  "common",
  "sender",
  "downer",
]
default-members = [
  "init",
]

[workspace.dependencies]
libc = "=0.2.174"
nix = { version = "0.30.1", features = ["ioctl", "socket"]}
sha2 = { version = "0.10", default-features = false }
reqwest = { version = "0.13.3", default-features = false }

