[package]
name = "common"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
publish = false

[dependencies]
libc = { workspace = true }
nix = { workspace = true, features = ["ioctl", "socket"]}
sha2 = { workspace = true, default-features = false }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "io-util"], default-features = false }
tokio-vsock = { workspace = true }

